---
- name: Lancer l'installation et la configuration de MongoDB
  include_tasks: mongodb.yml

- name: Lancer l'installation et la configuration de Prometheus
  include_tasks: prometheus.yml

- name: Lancer l'installation et la configuration de Grafana
  include_tasks: grafana.yml