- name: Supprimer les sources APT corrompues ou conflictuelles avant tout usage
  file:
    path: /etc/apt/sources.list.d/mongodb-org-7.0.list
    state: absent

- name: Update apt cache safely
  apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: yes

- name: Install Fail2Ban and UFW
  apt:
    name: ["fail2ban", "ufw"]
    state: present